### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by xujiangit** [mystorp/myagent#1]
现阶段hosts对域名要求太高了，不便于定制化。
能否加个配置开关，不检测hosts，直接全部代理，这样在使用时可以用其他的软件(cow或者meow之类的)进行分流。

**Comment by mystorp** [comment]
你好，@xujiangit 可能你还不是很了解这个项目的工作原理。这个项目没有读取 hosts 文件，而且这个项目我已经不维护了，还有，我现在不翻墙了。

**Comment by xujiangit** [comment]
@mystorp 谢谢回复，已经改代码解决了。
